// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH96lFZULMd4TDimyBDjFjzZDmwyOKX_g',
    appId: '1:120725006774:web:6c346cb278df2af7533917',
    messagingSenderId: '120725006774',
    projectId: 'cinemator-e44a0',
    authDomain: 'cinemator-e44a0.firebaseapp.com',
    storageBucket: 'cinemator-e44a0.firebasestorage.app',
    measurementId: 'G-YDP5KJP89G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJfb6_oUxDJr0zzrRWtWGVoeoventlVE',
    appId: '1:120725006774:android:322d21da485cff3c533917',
    messagingSenderId: '120725006774',
    projectId: 'cinemator-e44a0',
    storageBucket: 'cinemator-e44a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMz1gS9acnbP2YKPr82WM6HrB4Siz2MQ',
    appId: '1:120725006774:ios:86d4435935cc529b533917',
    messagingSenderId: '120725006774',
    projectId: 'cinemator-e44a0',
    storageBucket: 'cinemator-e44a0.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMz1gS9acnbP2YKPr82WM6HrB4Siz2MQ',
    appId: '1:120725006774:ios:86d4435935cc529b533917',
    messagingSenderId: '120725006774',
    projectId: 'cinemator-e44a0',
    storageBucket: 'cinemator-e44a0.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH96lFZULMd4TDimyBDjFjzZDmwyOKX_g',
    appId: '1:120725006774:web:a3cb50f4b25d629b533917',
    messagingSenderId: '120725006774',
    projectId: 'cinemator-e44a0',
    authDomain: 'cinemator-e44a0.firebaseapp.com',
    storageBucket: 'cinemator-e44a0.firebasestorage.app',
    measurementId: 'G-15LR4ZWBCV',
  );
}
